let response: any = {
    '$metadata': {
        httpStatusCode: 200,
        requestId: 'V0ZRJ8VFR9H1Y66V',
        extendedRequestId: 'YY7NL408eDUPlQr1Ln46mPeY3SgOW9q6DrF3ojnzB6zO0dClYDiktX9j1FzY8qqBAIXHyVDqtNg=',
        cfId: undefined,
        attempts: 1,
        totalRetryDelay: 0
    },
    AcceptRanges: 'bytes',
    LastModified: 2025-01 - 18T03: 56: 32.000Z,
    ContentLength: 272996,
    ETag: '"af44ee46c27b60c0ed13602bb3e9e2da"',
    ContentType: 'application/octet-stream',
    ServerSideEncryption: 'AES256',
    Metadata: {},
    Body: <ref * 1 > IncomingMessage {
        _events: {
            close: undefined,
            error: undefined,
            data: undefined,
            end: [Function: responseOnEnd
            ],
            readable: undefined
        },
        _readableState: ReadableState {
            highWaterMark: 65536,
            buffer: [],
            bufferIndex: 0,
            length: 0,
            pipes: [],
            awaitDrainWriters: null,
            [Symbol(kState)]: 1315084
        },
    _maxListeners: undefined,
    socket: TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        secureConnecting: false,
        _SNICallback: null,
        servername: 'esgi-android-project.s3.eu-west-3.amazonaws.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object: null prototype],
        _eventsCount: 11,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'esgi-android-project.s3.eu-west-3.amazonaws.com',
        _closeAfterHandlingError: false,
        _readableState: [ReadableState],
        _writableState: [WritableState],
        allowHalfOpen: false,
        _maxListeners: undefined,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: [HTTPParser],
        _httpMessage: [ClientRequest],
        autoSelectFamilyAttemptedAddresses: [Array],
        timeout: 0,
        [Symbol(alpncallback)]: null,
        [Symbol(res)]: [TLSWrap],
        [Symbol(verified)]: true,
        [Symbol(pendingSession)]: null,
        [Symbol(async_id_symbol)]: 31,
        [Symbol(kHandle)]: [TLSWrap],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(shapeMode)]: true,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: false,
        [Symbol(kSetKeepAlive)]: true,
        [Symbol(kSetKeepAliveInitialDelay)]: 1,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect - options)]: [Object]
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: false,
    rawHeaders: [
        'x-amz-id-2',
        'YY7NL408eDUPlQr1Ln46mPeY3SgOW9q6DrF3ojnzB6zO0dClYDiktX9j1FzY8qqBAIXHyVDqtNg=',
        'x-amz-request-id',
        'V0ZRJ8VFR9H1Y66V',
        'Date',
        'Sat,
            18 Jan 2025 13: 10: 53 GMT',
        'Last-Modified',
        'Sat,
            18 Jan 2025 03: 56: 32 GMT',
        'ETag',
        '"af44ee46c27b60c0ed13602bb3e9e2da"',
        'x-amz-server-side-encryption',
        'AES256',
        'Accept-Ranges',
        'bytes',
        'Content-Type',
        'application/octet-stream',
        'Content-Length',
        '272996',
        'Server',
        'AmazonS3'
    ],
    rawTrailers: [],
    joinDuplicateHeaders: undefined,
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 200,
    statusMessage: 'OK',
    client: TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        secureConnecting: false,
        _SNICallback: null,
        servername: 'esgi-android-project.s3.eu-west-3.amazonaws.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object: null prototype],
        _eventsCount: 11,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'esgi-android-project.s3.eu-west-3.amazonaws.com',
        _closeAfterHandlingError: false,
        _readableState: [ReadableState],
        _writableState: [WritableState],
        allowHalfOpen: false,
        _maxListeners: undefined,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: [HTTPParser],
        _httpMessage: [ClientRequest],
        autoSelectFamilyAttemptedAddresses: [Array],
        timeout: 0,
        [Symbol(alpncallback)]: null,
        [Symbol(res)]: [TLSWrap],
        [Symbol(verified)]: true,
        [Symbol(pendingSession)]: null,
        [Symbol(async_id_symbol)]: 31,
        [Symbol(kHandle)]: [TLSWrap],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(shapeMode)]: true,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: false,
        [Symbol(kSetKeepAlive)]: true,
        [Symbol(kSetKeepAliveInitialDelay)]: 1,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect - options)]: [Object]
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
        _events: [Object: null prototype],
        _eventsCount: 4,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        destroyed: false,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        maxRequestsOnConnectionReached: false,
        _defaultKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        strictContentLength: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        _closed: false,
        _header: 'GET /1237780b-d2af-48dc-a914-54d065544a67.jpg?x-id=GetObject HTTP/1.1\r\n' + 'host: esgi-android-project.s3.eu-west-3.amazonaws.com\r\n' + 'x-amz-user-agent: aws-sdk-js/3.588.0\r\n' + 'user-agent: aws-sdk-js/3.588.0 ua/2.0 os/darwin#24.2.0 lang/js md/nodejs#23.6.0 api/s3#3.588.0\r\n' + 'amz-sdk-invocation-id: 14335895-2d41-4b7d-9d28-5ecad51fb8ac\r\n' + 'amz-sdk-request: attempt=1; max=3\r\n' + 'x-amz-date: 20250118T131052Z\r\n' + 'x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\n' + 'authorization: AWS4-HMAC-SHA256 Credential=AKIA23FTT33WEAGZNP46/20250118/eu-west-3/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date;x-amz-user-agent, Signature=7b5cc793c73dd5d049213e332c72925b9aa766a3d29ca71e69ff4a322086c015\r\n' + 'Connection: keep-alive\r\n' + '\r\n',
            _keepAliveTimeout: 0,
                _onPendingData: [Function: nop],
                    agent: [Agent],
                        socketPath: undefined,
                            method: 'GET',
                                maxHeaderSize: undefined,
                                    insecureHTTPParser: undefined,
                                        joinDuplicateHeaders: undefined,
                                            path: '/1237780b-d2af-48dc-a914-54d065544a67.jpg?x-id=GetObject',
                                                _ended: false,
                                                    res: [Circular * 1],
                                                        aborted: false,
                                                            timeoutCb: [Function: emitRequestTimeout],
                                                                upgradeOrConnect: false,
                                                                    parser: [HTTPParser],
                                                                        maxHeadersCount: null,
                                                                            reusedSocket: false,
                                                                                host: 'esgi-android-project.s3.eu-west-3.amazonaws.com',
                                                                                    protocol: 'https:',
                                                                                        [Symbol(shapeMode)]: false,
                                                                                            [Symbol(kCapture)]: false,
                                                                                                [Symbol(kBytesWritten)]: 0,
                                                                                                    [Symbol(kNeedDrain)]: false,
                                                                                                        [Symbol(corked)]: 0,
                                                                                                            [Symbol(kChunkedBuffer)]: [],
                                                                                                                [Symbol(kChunkedLength)]: 0,
                                                                                                                    [Symbol(kSocket)]: [TLSSocket],
                                                                                                                        [Symbol(kOutHeaders)]: [Object: null prototype],
                                                                                                                            [Symbol(errored)]: null,
                                                                                                                                [Symbol(kHighWaterMark)]: 65536,
                                                                                                                                    [Symbol(kRejectNonStandardBodyWrites)]: false,
                                                                                                                                        [Symbol(kUniqueHeaders)]: null
                                                                                                                                    },
_eventsCount: 1,
    transformToByteArray: [AsyncFunction: transformToByteArray],
        transformToString: [AsyncFunction: transformToString],
            transformToWebStream: [Function: transformToWebStream],
                [Symbol(shapeMode)]: true,
                    [Symbol(kCapture)]: false,
                        [Symbol(kHeaders)]: {
    'x-amz-id-2': 'YY7NL408eDUPlQr1Ln46mPeY3SgOW9q6DrF3ojnzB6zO0dClYDiktX9j1FzY8qqBAIXHyVDqtNg=',
        'x-amz-request-id': 'V0ZRJ8VFR9H1Y66V',
            date: 'Sat,    18 Jan 2025 13: 10: 53 GMT',
                'last-modified': 'Sat,
    18 Jan 2025 03: 56: 32 GMT',
    etag: '"af44ee46c27b60c0ed13602bb3e9e2da"',
        'x-amz-server-side-encryption': 'AES256',
            'accept-ranges': 'bytes',
                'content-type': 'application/octet-stream',
                    'content-length': '272996',
                        server: 'AmazonS3'
},
[Symbol(kHeadersCount)
]: 20,
    [Symbol(kTrailers)
    ]: null,
        [Symbol(kTrailersCount)
        ]: 0
    }
}